### ISSUE TITLE
建议修改下概率分布，现在很多笔画繁多的字聚集在一堆，观感欠佳

### ISSUE THREAD

**Issue by Lorem3** [sooxin/Chinese-Lorem-Ipsum#2]
望采纳

**Comment by sooxin** [comment]
是的，以前为了实现方便而没有考虑字频，后续有时间我会试着优化一下。

**Comment by TML233** [comment]
是这样的，概率分布较好的例子有[这个](https://pinkylam.me/generator/chinese-lorem-ipsum/)，不过只有繁体的。

**Comment by Lorem3** [comment]
> 是这样的，概率分布较好的例子有[这个](https://pinkylam.me/generator/chinese-lorem-ipsum/)，不过只有繁体的。

根据天龙八部和其他小说统计的字频自己[做了一个](https://vitock.github.io/lorem-ipsum/)
